configobject/history/history.go
etc/schema/mysql/mysql.schema.sql

Depends on https://github.com/Icinga/icinga2/pull/7611

History: Add user notification history

---

configobject/history/history.go
etc/schema/mysql/mysql.schema.sql

Notification_history: Rename event_time to send_time

---

configobject/history/history.go
etc/schema/mysql/mysql.schema.sql

Flapping_history: Remove event_type

---

etc/schema/mysql/mysql.schema.sql

Schema: place environment_id always next to id

---

etc/schema/mysql/mysql.schema.sql
utils/convert.go

Comment_history: Remove comment_types downtime & flapping

---

utils/convert.go

Correct translation of nulls in {Notification,User}#{types,states}

---

config/config.go
icingadb.ini

Updates for packaging

---

configobject/history/history.go
configobject/statesync/statesync.go

Replace timers with sleeps

---

configobject/history/history.go
configobject/statesync/statesync.go
connection/mysql.go
connection/mysql_utils.go
connection/redis.go
ha/heartbeat.go
utils/benchmark.go
utils/convert.go

Correct and complete code docs

---

main.go

Handle SIGTERM and SIGINT

---

configobject/objecttypes/host/hoststate/hoststate.go
configobject/objecttypes/service/servicestate/servicestate.go
configobject/statesync/overdue.go
configobject/statesync/statesync.go
connection/redis.go
etc/schema/mysql/mysql.schema.sql
utils/convert.go

Schema: introduce {host,service}_state#is_overdue

---

configobject/history/history.go
configobject/statesync/statesync.go

Replace maps with hardcoded keys with structs

---

configobject/history/history.go
etc/schema/mysql/mysql.schema.sql

Schema: add acknowledgement_history

---

configobject/objecttypes/notification/notificationrecipient/notificationrecipient.go
etc/schema/mysql/mysql.schema.sql
main.go

Add notification recipients

---

etc/schema/mysql/mysql.schema.sql
ha/ha.go
ha/ha_test.go
ha/heartbeat.go

Schema: add endpoint_id, icinga2_version and icinga2_start_time to icingadb_instance

---

configobject/history/history.go
configobject/statesync/statesync.go

Make counters atomic

---

ha/ha.go
ha/ha_test.go

HA: Populate environment table

---

ha/ha.go
ha/ha_test.go

HA: Fix MySQL formatting

---

main.go
version.go

CLI: add -version flag

---

configobject/history/history.go
etc/schema/mysql/mysql.schema.sql

Depends on https://github.com/Icinga/icinga2/pull/7702

History: Add cancelled_by & removed_by to downtime & comment history

---

configobject/history/history.go
etc/schema/mysql/mysql.schema.sql
utils/convert.go

Schema: include consistent IDs, start time and end time in flapping and acknowledgement history

---

.github/workflows/go.yml

CI: also test with MariaDB 10.1

---

configobject/configsync/configsync.go

fixes #105 
depends on https://github.com/Icinga/icinga2/pull/7738

Runtime updates: Use one pub/sub channel per object type

---

ha/ha.go

HA: Make sure we still write our instance, if the table got truncated

---

.github/workflows/go.yml

CI: test also with MySQL 5.6 and 5.5

---

connection/mysql.go
connection/mysql_test.go
connection/redis.go
connection/redis_test.go

Don't panic on self-shutdown

---

configobject/objecttypes/checkcommand/checkcommand.go
configobject/objecttypes/eventcommand/eventcommand.go
configobject/objecttypes/host/host.go
configobject/objecttypes/host/hoststate/hoststate.go
configobject/objecttypes/notification/notification.go
configobject/objecttypes/notificationcommand/notificationcommand.go
configobject/objecttypes/service/service.go
configobject/objecttypes/service/servicestate/servicestate.go

Parse all time points and spans as float64

---

configobject/configsync/configsync.go
configobject/configsync/configsync_test.go
configobject/statesync/statesync.go
main.go
supervisor/supervisor.go

Fix config sync overwriting state sync

---

etc/schema/mysql/mysql.schema.sql

refs https://github.com/Icinga/icinga2/pull/7900

Schema: Comment & Downtime host_id should not be null

---

configobject/history/history.go
etc/schema/mysql/mysql.schema.sql

fixes #126 
blocked by https://github.com/Icinga/icinga2/pull/7906

Flapping History: Add percent_state_change_start/end

---

etc/schema/mysql/mysql.schema.sql

Schema: Fix MySQL 8 deprecation warnings

---

etc/schema/mysql/mysql.schema.sql

Schema: Add indices

---

etc/icingadb.service

A little oversight in the naming conventions.
fixes #144

Change icinga-redis to icingadb-redis in service file

---

.mailmap

This removes my damned dead name (This is not optional) and updates my mail to one GitHub knows (for clout) since the project was uploaded after I left the project.

Update my name and email

---

connection/mysql.go
connection/mysql_utils.go

Fix temporary SQL rows leak in SqlFetchChecksums()

---

configobject/objecttypes/host/hoststate/hoststate.go
configobject/objecttypes/service/servicestate/servicestate.go
configobject/statesync/statesync.go
utils/convert.go

Don't populate sticky acks as non-sticky

---

etc/schema/mysql/mysql.schema.sql

Schema: Change *command_argument.argument_order from tinyint to smallint

---

configobject/objecttypes/user/user.go

User: Fix NotificationsEnabled not cast to DB bool

---

configobject/statesync/overdue.go
go.mod
go.sum
utils/chunks.go
utils/chunks_test.go

Overdue: Make sure to chunk before updating in database

---

configobject/objecttypes/checkcommand/checkcommandargument/checkcommandargument.go
configobject/objecttypes/eventcommand/eventcommandargument/eventcommandargument.go
configobject/objecttypes/notificationcommand/notificationcommandargument/notificationcommandargument.go
connection/mysql_utils.go
connection/mysql_utils_test.go

*CommandArgument: Fix SetIf data type to accept any JSON data

---

configobject/statesync/overdue.go

This PR ensures, that overdue indicators never get updated in Redis before they successfully got updated in SQL.

Overdue: Fix indicators getting out of sync

---

configobject/history/history.go

History: correct event time of cancelled downtimes

---

doc/02-Installation.md

Add mysql flush privileges, -p option for import to db and enable system service at boot

Small fixes in doc

---

.github/workflows/go.yml

Keep testing w/ Go v1.14

---

.github/workflows/go.yml

Keep testing w/ MariaDB v10.4

---

ha/ha_test.go

Just a small fix for a wrong error message

Fix error message for MySQL in tests which previously said that Redis is not working

---

configobject/configsync/configsync_test.go
connection/redis.go
connection/redis_test.go
doc/03-Configuration.md
ha/ha_test.go
ha/heartbeat_test.go
icingadb.ini
main.go

Adds the missing password authentication.
fixes #204

Add Redis password authentication

---

connection/mysql_utils_test.go

ChunkRows(): ensure to never get an empty chunk

---

doc/03-Configuration.md
main.go

Add support mysql unix domain socket

---

etc/schema/mysql/mysql.schema.sql

Schema: correct comments in flapping_history, acknowledgement_history

---

etc/icingadb.service

This PR changes the service file to use the new YAML config instead of the old one.

Service File: Change config file in exec command to new YAML file

---

pkg/icingadb/db.go
pkg/icingadb/runtime_updates.go
pkg/icingadb/sync.go

Activate and use bulk upsert

---

pkg/icingadb/v1/state.go
schema/mysql/schema.sql
schema/mysql/upgrades/1.0.0-rc2.sql

fixes #317
refs Icinga/icinga2#8916

Icinga DB: introduce Checkable#last_comment_id

---

cmd/icingadb/main.go

... as append(x,y) would modify x.
fixes #324

Don't append(x,y) if x is not to be modified

---

pkg/driver/driver.go

The MySQL driver logs something like unexpected EOF, busy buffer,
broken pipe, bad connection, invalid connection etc. in the event
of an error. Most of these are retryable and are handled either by
the MySQL driver or our retry logic. Previously these messages
were discarded, but since they can be useful when debugging
connectivity issues, we'll now log them with the debug severity as
otherwise they would add too much noise to the logs where you might
see error messages with no actual effect.

Log MySQL driver errors at the debug level instead of discarding them

---

schema/mysql/schema.sql
schema/mysql/upgrades/1.0.0-rc2.sql

I.e. large enough for "host.name!service.name!UUID".
fixes #273

Enlarge {comment,downtime}#name 255 -> 548

---

internal/command/command.go
internal/version.go
pkg/config/config.go

Support --version

---

pkg/icingadb/v1/downtime.go
pkg/icingadb/v1/history/downtime.go
schema/mysql/schema.sql
schema/mysql/upgrades/1.0.0-rc2.sql

Introduce downtime#scheduled_by

---

pkg/icingadb/objectpacker/objectpacker.go
pkg/icingadb/v1/customvar.go

It always packs a slice, even if only one item given.

Clarify what MustPackAny() does

---

cmd/icingadb/main.go
pkg/icingadb/ha.go

... not to hang for 5m if DB is down.
fixes #350

On shutdown: give up HA handover after 3s, not 5m

---

pkg/icingaredis/client.go

The first iteration of the PR handled this in the delta algorithm, this iteration simply discards duplicates right when reading from Redis.
<details>
<summary>Original PR description for reference</summary>
Initially I hoped that one could simply read both channels until the end, just writing the items in a map each (thereby removing duplicates) would suffice, but my tests showed that with a million of objects, this already takes over a second so I think it makes sense to keep the approach to compute the delta on the fly while receiving the data.
The new implementation is now single-threaded, eliminating the need for locking. My tests showed that this gives a slight penalty when only considering the wall clock time from start to finish (about 20% to 30% in my tests), however, the CPU time …

Redis HYield: remove duplicates returned by HSCAN

---

pkg/icingadb/v1/history/state.go
pkg/icingadb/v1/state.go
schema/mysql/schema.sql
schema/mysql/upgrades/1.0.0-rc2.sql

Include CheckResult#scheduling_source in state and history

---

doc/03-Configuration.md
pkg/config/config.go
pkg/config/database.go
pkg/config/redis.go

Support TLS

---

cmd/icingadb/main.go
pkg/icingadb/history/sync.go
pkg/icingadb/v1/history/meta.go
pkg/icingadb/v1/history/notification.go
pkg/icingadb/v1/history/state.go
schema/mysql/schema.sql
schema/mysql/upgrades/1.0.0-rc2.sql

Make {NotificationHistory,StateHistory,History*}#Id UUID -> SHA1

---

cmd/icingadb/main.go

Sync history independent of HA

---

pkg/icingadb/db.go
pkg/icingaredis/client.go

This PR fixes CamelCase config keys and adds missing validation.

Fix flawed config keys and validation

---

.mailmap
AUTHORS

Update authors and remove authors whose code is no longer in the repo

---

.github/workflows/go.yml

If this changes go.*, complain about the non-perfect file(s).

GHA: go mod tidy

---

pkg/icingadb/ha.go
pkg/types/unix_milli.go
pkg/utils/utils.go
tests/cleanup_and_retention_test.go

and remove redundant utils.UnixMilli().
* #452

Do x.UnixMilli(), not utils.UnixMilli(x)

---

doc/03-Configuration.md
pkg/config/database.go

Support *nix sockets as documented

---

pkg/icingadb/ha.go

for non-responsible instances.

Ensure icingadb_instance#responsible=n

---

pkg/icingadb/overdue/get_overdues.lua
pkg/icingadb/overdue/sync.go

for the sake of syntax highlighting.

go:embed LUA script

---

pkg/icingadb/db.go
pkg/icingadb/v1/command.go
schema/mysql/schema.sql
schema/mysql/upgrades/1.0.0.sql
schema/pgsql/schema.sql

Add CommandArgument#Separator

---

pkg/config/redis.go
pkg/driver/driver.go
pkg/retry/retry.go

This PR aligns the behavior of the IsRetryable functions for Redis and database. It now also checks if the error implements timeout, even if the error implements temporary, where previously only the temporary bool was returned and timeout was ignored. The idea here is that an error could implement both, returning false for temporary and true for timeout. Also, all DNS errors are now considered retryable.

Streamline IsRetryable functions and retry DNS errors

---

pkg/version/version.go

When building Icinga DB from a tarball generated using `git archive` using a Git version older than 2.32, the version output could incorrectly state "Icinga DB version: %(describe)". This commit detects this situation and implements a fallback.
Build the docker container locally (i.e. using `build.bash`), this uses `git archive` and Git 2.20.1
```console
$ docker run --rm -it icinga/icingadb:dev /icingadb --version
Icinga DB version: %(describe)
Build information:
Go version: go1.18.2 (linux, amd64)
Git commit: 64aca11bcbfc0462caf12e43cdc423851d866b40
```
```console
$ docker run --rm -it icinga/icingadb:dev /icingadb --version
Icinga DB version: 1.0.0-rc2-gcd78d96
Build information:
Go version: go1.18.2 (linux, amd64)
Git commit: cd78d96f047b5eb5577dc4d7acf75926930be1f7
```
Note: compared …

Fix `icingadb --version` output when using older Git versions

---

doc/02-Installation.md

This allows the user to additionally connect via ::1 and Unix Domain Sockets.
fixes #494

Docs: use @localhost instead of @127.0.0.1 for MySQL user

---

cmd/icingadb/main.go

Make Database/Redis schema mismatch error more user friendly

---

pkg/driver/driver.go
pkg/icingaredis/telemetry/heartbeat.go
pkg/icingaredis/telemetry/stats.go

My proposed changes to #464 (corresponding Icinga 2 PR: https://github.com/Icinga/icinga2/pull/9416)

Icinga DB Check: Proposed changes to #464

---

cmd/icingadb/main.go
config.example.yml
doc/02-Installation.md
doc/03-Configuration.md
pkg/com/atomic.go
pkg/driver/driver.go
pkg/icingadb/cleanup.go
pkg/icingadb/db.go
pkg/icingadb/ha.go
pkg/icingadb/history/retention.go
pkg/icingadb/history/sync.go
pkg/icingadb/overdue/sync.go
pkg/icingadb/runtime_updates.go
pkg/icingadb/sync.go
pkg/icingaredis/client.go
pkg/icingaredis/heartbeat.go
pkg/icingaredis/telemetry/heartbeat.go
pkg/icingaredis/telemetry/stats.go

for being monitored by Icinga.
```
127.0.0.1:6379> xread block 0 streams icingadb:telemetry:stats 0-0
1) 1) "icingadb:telemetry:stats"
2) 1) 1) "1652788675223-0"
2) 1) "sync_config"
2) "2065"
3) "sync_state"
4) "12"
2) 1) "1652788676224-0"
2) 1) "sync_config"
2) "3792"
3) "sync_history"
4) "13"
127.0.0.1:6379>
```
for pending updates amount.
```
127.0.0.1:6379> xread block 0 streams icingadb:telemetry:heartbeat 0-0
1) 1) "icingadb:telemetry:heartbeat"
2) 1) 1) "1652788675227-0"
2)  1) "ha:has-heartbeat"
2) "1"
3) "ha:is-responsible"
4) "1"
5) "ha:other-responsible"
6) "0"
7) "db-err"
8) ""
9) "version"
10) "v1.0.0-rc2-dev"
127.0.0.1:6379>
```

Write own status into Redis

---

.github/ISSUE_TEMPLATE/release.md

Square brackets are a problem and have to be quoted.
PR from a fork because this allows for a live demonstration that this works:
* https://github.com/icinga/icingadb/issues/new/choose **does not** show the template.
* https://github.com/julianbrost/icingadb/issues/new/choose **does** show the template.

Fix release issue template

---

CHANGELOG.md
internal/version.go

* #534
* #536
* #540
refs #539

Release 1.1.0

---

.github/workflows/docker.yml

GHA: handle changed interface of Icinga/docker-icingadb

---

doc/icingadb-migration.example.yml

icingadb-migrate: document TLS support

---

doc/04-Upgrading.md

Same commit/PR as #637 but for the `main` branch instead of `support/1.1`.

doc/04-Upgrading.md: Fix path for schema upgrades

---

pkg/retry/retry.go

Retry broken pipe errors (`EPIPE`)

---

doc/02-Installation.md

Since I just did a good old-fashioned Icinga DB installation using PostgreSQL on a vanilla Debian system, there were several tripwires I successfully stumbled upon while following our PostgreSQL installation docs. And this is far from the first time I have installed an Icinga DB.
First, I changed the order to put the requirements before the commands that require them. Otherwise, following the documentation from top to bottom will result in errors that will be addressed later.
In addition, I added a sentence about where to find the pg_hba.conf. I also explained how to tighten up network-based access and the availability of more modern hash algorithms on almost all of the operating systems we target.
Since the vanilla Debian I was using had almost no locales, PostgreSQL was unhappy about …

doc/02-Installation.md: More PostgreSQL details

---

cmd/icingadb/main.go
pkg/icingadb/ha.go

ha: More logging in OnRetryableError in HA.realize
The current state of the OnRetryableError function for the inner
function in HA.realize was designed quite silent. In this changed
version reoccurring errors will be logged and the log level after the
first three attempts was raised to warning. Additionally, the current
attempt and the total duration will be logged as well.
---
icingadb: Abort with a message instead of a stack trace
When the icingadb application was aborted with a fatal log event, the
user received an impressive stack trace. Unfortunately, the relevant
information is not directly visible for the untrained eye.
This change now prints a normal log event at FATAL level with an error
attached. If an error implements the fmt.Formatter, the zap logging
framework adds both an …

Small Logging Rework: More logging in OnRetryableError in HA.realize and abort with a message instead of a stack trace

---

cmd/icingadb-migrate/main.go

Setting an explicit logger for the two database connections shows faulty connection attempts directly when they occur and not only after the retry timeout of five minutes.
References #949.
----
<details><summary>Output with invalid database config before this change.</summary>
<p>
```
2025-05-07T09:04:07.995+0200    INFO    icingadb-migrate/main.go:82     Starting IDO to Icinga DB history migration
2025-05-07T09:04:07.995+0200    INFO    icingadb-migrate/main.go:179    Connecting to databases
2025-05-07T09:09:08.029+0200    FATAL   icingadb-migrate/main.go:208    dial tcp [::1]:3306: connect: connection refused
retry deadline exceeded
github.com/icinga/icinga-go-library/retry.WithBackoff
/home/apenning/go/pkg/mod/github.com/icinga/icinga-go-library@v0.6.3/retry/retry.go:100 …
```

icingadb-migrate: Logger for Database connections

---

doc/07-Operations.md

This PR adds a little bit of Redis tuning to the operations section of the documention.
The procedure described helped to reduce memory consumption in a huge Icinga setup significantly.

Add a Redis tuning note about huge setups

---

doc/02-Installation.md

Mention the existence of the "icingadb-selinux" package for some distributions, as mentioned in #580.

docs: Mention icingadb-selinux package
