Icinga/icingadb

- config/config.go
- icingadb.ini
- main.go
Depends on #1
```
$ ./icingadb
INFO[0000] Connecting to Redis
INFO[0000] Connecting to MySQL
INFO[0000] Redis connection established
ERRO[0000] Could not connect to SQL. Trying again        context=sql error="Error 1045: Access denied for user 'module-dev'@'localhost' (using password: YES)"
INFO[0000] Starting heartbeat listener
INFO[0000] Serving metrics at http://0.0.0.0:8080/metrics
FATA[0000] listen tcp 0.0.0.0:8080: bind: address already in use
```
```
$ ./icingadb
INFO[0000] Connecting to Redis
INFO[0000] Connecting to MySQL
INFO[0000] Redis connection established
ERRO[0000] Could not connect to SQL. Trying again        context=sql error="Error 1045: Access denied for user 'module-dev'@'localhost' (using password: YES)"
INFO[0000] Starting heartbeat listener
```
```
[metrics] …
```
> Allow to configure metrics listener, off by default

- configobject/objecttypes/host/hoststate/hoststate.go
- configobject/objecttypes/service/servicestate/servicestate.go
This is needed, because 2 attributes with the same JSON tag result in 2 empty attributes on JSON unmarshal.
> State: Read hard_state/last_hard_state only once

- etc/schema/mysql/mysql.schema.sql
> Schema: add table icingadb_schema

- etc/schema/mysql/mysql.schema.sql
We currently use both `DEFAULT NULL` and `NULL DEFAULT NULL` randomly
> Schema: Use DEFAULT NULL everywhere & fix table options

- configobject/configsync/configsync.go
Runtime updates for object types without a checksum didn't work because we always insert every ID into our update worker queue. The update worker queue will never be worked on, if an object type has no checksum. With this PR, we insert objects without checksum into our insert queue instead.
> Fix runtime updates for object types without checksum

- doc/02-Installation.md
The `icinga-redis` package is now available in all testing repositories.
fixes #140
> Docs: Remove release repo info

- connection/mysql.go
- connection/mysql_utils.go
- connection/mysql_utils_test.go
This fixes a "too many placeholders" exception caused by large nested custom vars.
Custom vars get flattened by calling `getFinalRows()` on custom var rows.
https://github.com/Icinga/icingadb/blob/49891dfa1b0560dcd038241454f27f13c3a0e8d4/connection/mysql.go#L695
This extends the chunk size of 500 rows, provided by our Redis implementation, by an unlimited amount.
Test config:
```
numHosts = 500
for (hid in range(numHosts)) {
object Host "TestHost - " + hid use (hid) {
check_command = "dummy"
vars.perp = {}
var numPerpVars = 500
for (i in range(numPerpVars)) {
vars.perp["var" + i] = i + "_" + hid
}
}
}
```
This PR might also be the solution for #147, but that needs testing.
> MySQL: Make sure to chunk rows correctly

- etc/schema/mysql/mysql.schema.sql
`name_ci` is the column used by Icinga DB Web to perform quick searches, so indexing it is required.
Also adds indices for `name` and `display_name` to tables `user` and `usergroup`. Just like it is already the case for tables `host` and `service`.
> mysql/schema: Add name indices to host,service,user,usergroup tables

- connection/mysql_utils.go
Avoiding float arithmetic avoids precision problems. I don't think this results in any bugs for values we realistically reach in Icinga DB, but why use floats if you don't have to? Then you also don't have to think about whether doing so may blow up.
> ChunkRows: replace float with int arithmetic

- configobject/configsync/configsync.go
- connection/redis.go
- connection/redis_test.go
- utils/chunks.go
- utils/chunks_test.go
Redis documentation states that it is preferable to use `*SCAN` instead of `*KEYS` (https://redis.io/commands/keys):
<blockquote>
Warning: consider KEYS as a command that should only be used in production environments with extreme care. It may ruin performance when it is executed against large databases. This command is intended for debugging and special operations, such as changing your keyspace layout.  Don't use KEYS in your regular application code. If you're looking for a way to find keys in a subset of your keyspace, consider using SCAN or sets.
</blockquote>
While the documentation is for the KEYS command and not HKEYS, the same warning should apply here to as the hashes we are iterating over can get quite large. Therefore use the HSCAN command that exists as an alternative.
In …
> Config Sync: Iterate over config using cursor (replace HKEYS with HSCAN)

- configobject/configsync/configsync.go
- configobject/configsync/configsync_test.go
- configobject/configsync/ha.go
- configobject/configsync/ha_test.go
- connection/mysql.go
- connection/mysql_test.go
- ha/ha.go
- ha/ha_test.go
- ha/heartbeat.go
- ha/state.go
- main.go
Make the HA takeover mechanism concurrency-safe. The general idea is to insert a row into `icingadb_instance` for each instance that reflects the responsible status of the instance. When trying to take over, a serializable SQL transaction is used to check the status of all other instances and update the current instance to the responsible state.
The PR also moves some code from the `ha` package to `configobject/configsync` which was very specific to the config sync and instead provides a generic mechanism to get notified about HA state changes in the `ha` package.
* Change type of `icingadb_instance.id` from `binary(16)` to `binary(20)`: it now stores a SHA1 hash instead of an UUID
* Introduce a column `icingadb_instance.startup_id`: detect multiple instances sharing the same ID by …
> HA: Prevent multiple instances from taking over at the same time

- configobject/statesync/overdue.go
- configobject/statesync/statesync.go
- connection/redis.go
- main.go
Syncing the overdue flag to the host_state and service_state tables was not HA-aware and assumed to have a consistent copy of all serivces/hosts with overdue set stored in Redis. However, if a second Icinga DB instance was active, this set might have become outdated.
This commit fixes this by making the overdue sync HA-aware, i.e. pausing it if the current instance is inactive. Additionally, it fetches the set of overdue services from MySQL and syncs it back to Redis when becoming active.
fixes #197
fixes #233
* Removing left-over overdue flags:
1. `UPDATE service_state SET is_overdue = 'y';`
2. Verify that all services show up as overdue in the web interface
3. Restart the active Icinga DB instance
4. Verify that all all superfluous overdue states are gone
* Adding missing overdue flags: …
> Make overdue sync HA-aware

- schema/1.0.0-rc2.sql
- schema/mysql.schema.sql
This PR
* applies all changes from the existing `1.0.0-rc2.sql` file to the `mysql.schema.sql` file so that it represents the current version of the schema
* adds all changes done to `mysql.schema.sql` since the `v1.0.0-rc1` git tag to the `1.0.0-rc2.sql` file
* inserts schema version 2 into the `icingadb_schema` table
The diff between applying the initial schema and applying the rc1 schema and then the upgrade file now looks as follows:
```
$ docker run --rm -p 127.30.177.65:3306:3306 -it -e MYSQL_ROOT_PASSWORD=root mariadb:latest &
$ mysql -h127.30.177.65 -uroot -proot -e 'CREATE DATABASE a; CREATE DATABASE b;'
$ mysql -h127.30.177.65 -uroot -proot a < schema/mysql.schema.sql
$ cat <(git show v1.0.0-rc1:etc/schema/mysql/mysql.schema.sql) schema/1.0.0-rc2.sql | mysql -h127.30.177.65 …
```
> Integrate 1.0.0-rc2 schema

- pkg/icingadb/ha.go
This was introduced by 621c1b953737a8983ba9701da8f01fc5426000c3 and leads to `tx.Commit()` always returning an "context canceled" error.
> HA: context used to start transaction must not be canceled before the transaction is committed

- cmd/icingadb/main.go
The customvar runtime update sync may change because the customvar
flat runtime update sync is not yet implemented.
> Add custom vars to the runtime update sync

- pkg/icingadb/ha.go
The transmission processes of the handover and takeover channel can
block because in the event of a context cancellation, nobody reads
it anymore.
> HA: Respect context when operating channels

- .github/ISSUE_TEMPLATE/bug_report.md
Add an issue template to have another big button for bug reports on https://github.com/Icinga/icingadb/issues/new/choose
Based on the Icinga 2 issue template. I omitted feature requests for now, I think we should get to 1.0 first before we think of additional feature requests.
> Add issue template for bug reports

- schema/mysql/schema.sql
- schema/mysql/upgrades/1.0.0-rc2.sql
#281 changed the pk in tables `host_state` and `service_state` to column `id`. This means that there is no index anymore on `host_id` and `service_id` on which Icinga DB Web heavily relies upon. The result was a full table scan for joins to these tables and heavily degraded performance.
This re-adds those indices.
> schema: Re-add indices for `host_id` and `service_id` in state tables

- schema/mysql/schema.sql
- schema/mysql/upgrades/1.0.0-rc2.sql
This ensures that 'n' < 'y' when sorting, as you'd expect when either comparing the alphabetical order of both values or the corresponding 0/1 values for a boolean.
fixes #234
> MySQL schema: reverse order of entries in enums for boolean to fix sort order

- schema/mysql/schema.sql
- schema/mysql/upgrades/1.0.0-rc2.sql
`mediumtext` is a tradeoff between `text` and `longtext`; `text` being too short and `longtext` being too big.
fixes #199
> Change output, long_output and performance_data columns to mediumtext

- pkg/com/cond.go
- pkg/icingadb/ha.go
- pkg/icingaredis/heartbeat.go
Heartbeat now uses pointer receivers for its methods because some methods actually change the heartbeat values. The context is no longer stored in the structure, but passed to the controller loop. The beat and the lost channels are replaced by Cond and the last heartbeat is stored independently to not be affected by a slow HA receiver. If the database connections are occupied by the config, HA cannot update the instance and does not read from the beat channel in time. In addition, heartbeat errors are no longer swallowed, but handled in HA.
fixes #316
Please note that I think it also makes sense to use a separate connection pool for HA, but that's subject to a different PR.
> Pointer receivers, Cond usage, pass ctx and Godoc for Heartbeat

- cmd/icingadb/main.go
- pkg/icingadb/runtime_updates.go
- pkg/icingaredis/utils.go
Icinga now sends runtime updates in two separate channels,
icinga:runtime for config updates and icinga:runtime:state for
state updates. With this change, Icinga DB reads from these two
streams. This is a preparation so that state updates can be
streamed directly after a (re)start of Icinga or Icinga DB without
waiting for the config sync, as it is currently done.
refs Icinga/icinga2#8915
> Stream state updates from icinga:runtime:state

- pkg/icingadb/v1/history/ack.go
- schema/mysql/schema.sql
- schema/mysql/upgrades/1.0.0-rc2.sql
... for the case an ack_set event happened before Icinga DB history recording.
fixes #305
closes #318
> Allow acknowledgement_history#{author,is_sticky,is_persistent} being NULL

- pkg/icingadb/db.go
ErrBadConn is returned by a driver to signal that a driver.Conn is
in a bad state. We have to retry with these errors as well.
> Also retry driver.ErrBadConn

- schema/mysql/schema.sql
As of version 8, MySQL is stricter when it comes to setting system
and session variables and requires that the user importing our schema
be granted the SESSION_VARIABLES_ADMIN permission. Although the session
scope is already the default, we will now use SET SESSION for the modes
in our scheme for the sake of clarity.
> Use SET SESSION for schema modes

- pkg/icingadb/v1/downtime.go
- pkg/icingadb/v1/history/downtime.go
- schema/mysql/schema.sql
- schema/mysql/upgrades/1.0.0-rc2.sql
This PR adds the downtime attribute `parent_id` added to Icinga 2 with https://github.com/Icinga/icinga2/pull/8913 to Icinga DB.
> Downtime: Add parent_id

- pkg/config/database.go
- pkg/config/redis.go
- pkg/icingadb/db.go
- pkg/icingaredis/client.go
Instead of mixing required and optional configuration, there is now the options key for optional database and Redis configuration. In addition, the configuration of 0 for database max_connections and Redis timeout is no longer allowed, since 0 stands for deactivate.
> Separate required and optional configuration for database and Redis

- pkg/config/config.go
- pkg/config/database.go
- pkg/config/redis.go
- pkg/icingadb/db.go
- pkg/icingaredis/client.go
YAML is decoded by the structure of the YAML source document, not the Go destination data structure. Therefore, the old code did not always call `UnmarshalYAML()` on all sub-structs. Therefore, defaults were not always set but zero values were used, resulting in all kind of strange behavior.
This commit changes the code so that it no longer relies on individual `UnmarshalYAML()` functions to set the defaults for each sub-struct but instead just sets all of them when creating the surrounding Config instance. It also moves the config validation to separate Validate() functions.
<details>
<summary>Extra patch to show parsed config</summary>
```diff
diff --git a/cmd/icingadb/main.go b/cmd/icingadb/main.go
index daf7461..dcd8fbf 100644
--- a/cmd/icingadb/main.go
+++ b/cmd/icingadb/main.go
@@ …
```
> Ensure extra config options are properly initialized

- pkg/icingaredis/heartbeat.go
Has to use the `Warnw` function as it passes additional zap attributes.
```
2021-09-23T09:16:33.902+0200	WARN	icingaredis/heartbeat.go:149	Lost Icinga 2 heartbeat{timeout 8 60000000000  <nil>}
```
```
2021-09-23T09:29:30.913+0200	WARN	icingaredis/heartbeat.go:149	Lost Icinga 2 heartbeat	{"timeout": "1m0s"}
```
> Fix use of wrong log function on heartbeat loss

- pkg/com/counter.go
- pkg/contracts/contracts.go
- pkg/icingaredis/client.go
This PR addresses the following data races that can occur if an ongoing config sync is canceled:
`counter.go`:
```
WARNING: DATA RACE
Read at 0x00c03212e4a0 by goroutine 786:
github.com/icinga/icingadb/pkg/icingaredis.(*Client).HYield.func1.1()
/Users/elippmann/Workspace/icingadb/pkg/icingaredis/client.go:57 +0xa4
github.com/icinga/icingadb/pkg/utils.Timed()
/Users/elippmann/Workspace/icingadb/pkg/utils/utils.go:75 +0x61
github.com/icinga/icingadb/pkg/icingaredis.(*Client).HYield.func1()
/Users/elippmann/Workspace/icingadb/pkg/icingaredis/client.go:71 +0x51f
golang.org/x/sync/errgroup.(*Group).Go.func1()
/Users/elippmann/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x94
Previous write at 0x00c03212e4a0 by goroutine 986:
sync/atomic.AddInt64() …
```
> Fix data races

- pkg/config/redis.go
- pkg/driver/driver.go
- pkg/icingadb/db.go
- pkg/retry/retry.go
E.g. the first "connection refused", the first "hostname mismatch" and the all-clear.
fixes #351
> Log all different failed and recovered reconnects to backends

- go.mod
- pkg/icingadb/delta.go
- pkg/icingadb/delta_test.go
The current delta implementation uses two goroutines that read from their own channels but update shared maps all the time. Rewriting it to just use a single goroutine make almost no difference in wall clock time (seems to even be a little faster) but removes quite a lot of lock contention so that the total CPU time needed decreases quite a bit.
For the following test, I increased the limit in the benchmark (didn't want to commit this as that test needs about 12GB RAM).
```console
$ go test -o test -c github.com/icinga/icingadb/pkg/icingadb
$ ./test -test.bench=.
goos: linux
goarch: amd64
pkg: github.com/icinga/icingadb/pkg/icingadb
cpu: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
BenchmarkDelta/1024-8         	    1310	    793142 ns/op
BenchmarkDelta/2048-8         	     800	   1518578 …
```
> Rewrite delta to use only a single goroutine

- doc/03-Configuration.md
We already have config.yml.example as a source to copy and paste
so one can get started easily. In addition,
only one place has to be maintained for the example configuration.
This PR should be merged before #366.
> Remove example configuration from docs

- schema/mysql/schema.sql
- schema/mysql/upgrades/1.0.0-rc2.sql
... to make MySQL storage capabilities of likely large text columns more similar (16MB -> 4GB) to (upcoming) Postgres ones (unlimited) and not to have to pre-truncate anything.
fixes #260
closes #218
> Schema: s/mediumtext/longtext/

- cmd/icingadb/main.go
- config.yml.example
- doc/03-Configuration.md
- internal/command/command.go
- internal/logging/logging.go
- pkg/config/config.go
- pkg/config/logging.go
This PR implements user-configurable child logger levels and the default log level via a new configuration section called `logging`. In addition, each component in Icinga DB now uses a specific child logger, e.g. `ha`, `*-sync`, etc.
With this PR the default log level is set to `INFO`.
> Child loggers

- pkg/icingadb/ha.go
- pkg/icingaredis/heartbeat.go
- pkg/retry/retry.go
The first commit in the series replaces the functions `Beat()`, `Loss()` and `Message()` on `Heartbeat` with a single `Events()` function that returns a channel to which (a) a non-nil pointer is sent for each heartbeat and (b) a nil pointer is sent on a heartbeat loss. This allows the HA code to not miss any heartbeat loss events (technically it can still miss one but only if it fails to receive from the channel before an other heartbeat is received from Icinga 2, but in this case the information of a heartbeat loss became obsolete anyways).
The remaining three commits add a timeout for writing a heartbeat to the SQL database (happening in `HA.realize()`). If this does not finish before the heartbeat expires, it (a) gives up writing to the database and (b) signals a handover to the local …
> Reliably handle heartbeat events in HA and stop writing a heartbeat to the DB after it expires and hand over

- cmd/icingadb/main.go
- pkg/common/sync_subject.go
- pkg/contracts/contracts.go
- pkg/icingadb/db.go
- pkg/icingadb/runtime_updates.go
- pkg/icingadb/sync.go
- pkg/icingadb/v1/customvar.go
- tests/object_sync_test.go
This PR implements custom var flat handling in runtime updates. Custom vars must also be handled explicitly for this, because the original values are used to extract the flat ones.
In addition, this PR removes `contracts.EntitiyFactoryFunc.WithInit()` which checked for `contracts.Initer` every time. Now it is only done once in `common.NewSyncSubject()`.
1. Make sure there is no custom variable named `cv`:
```sql
MariaDB [icingadb]> SELECT cvflat.flatname, cvflat.flatvalue FROM customvar_flat cvflat INNER JOIN customvar cv ON cvflat.customvar_id = cv.id WHERE cv.name = "cv";
Empty set (0.002 sec)
```
2. Create a host via the Icinga API with a custom variable named `cv`:
```bash
curl -k -u user:password -H 'Accept: application/json' -X PUT 'https://localhost:5665/v1/objects/hosts/test-host' …
```
> Sync customvar flat runtime updates

- cmd/icingadb/main.go
- pkg/contracts/contracts.go
- pkg/icingadb/db.go
- pkg/icingadb/ha.go
- pkg/icingadb/scoped_entity.go
- pkg/icingadb/sync.go
- pkg/icingadb/v1/environment.go
- pkg/icingadb/v1/v1.go
- pkg/icingaredis/heartbeat.go
- pkg/icingaredis/v1/icinga_status.go
- schema/mysql/schema.sql
- schema/mysql/upgrades/1.0.0-rc2.sql
- tests/environment_test.go
This PR improves how Icinga DB handles multiple environments. It's based on #336 and supersedes that PR. The changes are:
* Populate the `environment` table (#292)
* Make use of a new environment ID specific to Icinga DB as introduced by https://github.com/Icinga/icinga2/pull/9036 (new in this PR compared to #336)
* As the environment ID now shouldn't ever change, just bail out when it still does (changed from #336, that PR tried to handle it gracefully but it still had edge-cases where it could potentially write to the wrong environment)
* Restrict delta computation to current environment
* The environment name is currently just set to the ID and no mechanism is provided to update it. It can just be set in the database and Icinga DB won't reset it. icingadb-web could later provide a …
> Better handling of multiple environments

- cmd/icingadb/main.go
- pkg/icingadb/v1/command.go
- pkg/icingadb/v1/notification.go
- schema/mysql/schema.sql
- schema/mysql/upgrades/1.0.0-rc2.sql
This PR changes the command reference IDs to `{check,notification,event}command_id` to have unified reference IDs (`{tablename}_id`) across our schema where possible.
- PR Icinga 2: https://github.com/Icinga/icinga2/pull/9058
- PR Icinga DB Web: https://github.com/Icinga/icingadb-web/pull/406
TODO:
> Schema: Prefix command_id with command type (check, event, notification)

- schema/mysql/schema.sql
- schema/mysql/upgrades/1.0.0-rc2.sql
This PR fixes 2 typos in index names and a missing comment change introduced in #385
> Schema: Fix index typos + missing comment change

- pkg/retry/retry.go
dc7511c introduced a parent context check to suppress logging if
it was canceled.
If it was not canceled, the check overwrites the variable err,
which resets every previous real error to nil,
which then leads to fatals because the OnError callback or
the IsRetryable function expect a non-nil error.
Since I cannot reproduce which logs should have been suppressed by
the changes, I removed them completely.
> Fix broken retry mechanics

- tests/go.mod
- tests/go.sum
- tests/history_test.go
- tests/history_test_zones.conf
This PR extends the existing history sync integration tests so that these are also run with an icinga2 HA cluster to check that even in this case, no duplicates are written to MySQL.
This served as my tests for the following pull requests:
* #392 (merged into this PR for testing)
* #393 (merged into this PR for testing)
* https://github.com/Icinga/icinga2/pull/9029 (the `icinga2:git-v2.13.0-77-ga17592fe7` Docker image is a build of that PR merged with the current master (https://github.com/Icinga/icinga2/commit/b5132a59ef72737fd7c3415cf101c5c1ff1c32dc)
* https://github.com/Icinga/icinga-testing/pull/7
> Integration tests for history sync in HA setups

- pkg/icingadb/v1/notification.go
Having `NotificationUser` as part of `NotificationRecipient`, just because they share a few attributes, makes the structure a bit confusing.
> Make NotificationRecipient struct readable

- cmd/icingadb/main.go
Use dedicated connections for heartbeat and HA to ensure that
heartbeats are always processed and the instance table is updated.
Otherwise, the connections can be too busy due to the
synchronization of configuration, status, history, etc.,
which can lead to handover / takeover loops because the heartbeat
is not read while HA gets stuck when updating the instance table.
> Use own connections for heartbeat and HA

- schema/mysql/schema.sql
- schema/mysql/upgrades/1.0.0-rc2.sql
refs https://github.com/Icinga/icingadb-web/issues/404
> Add more MySQL indexes

- tests/go.mod
- tests/go.sum
- tests/internal/utils/slice.go
- tests/internal/utils/slice_test.go
- tests/object_sync_test.conf
- tests/object_sync_test.go
This PR adds tests for notifications including relations (user, usergroup and recipient).
Runtime update tests for users didn't really update anything until now, but only created new ones. This has been changed and now updates the same object over and over for testing.
> Integration tests: Add notifications and improve user runtime updates

- pkg/config/redis.go
- pkg/utils/utils.go
The default Redis `PoolSize` is `10 * CPU`, which isn't enough to run Icinga DB on machines with only 1 CPU.
Most of our open connections come from blocking XREADs. (e.g. Heartbeat, Runtime, Overdue, History)
fixes #425
> Make sure Redis connection pool is large enough

- doc/02-Installation.md
Adds a missing `-` to the config parameter of the foreground command.
> Docs: Fix foreground command config parameter

- doc/02-Installation.md
Newer MySQL versions (8+) no longer allow using the `GRANT + IDENTIFIED BY` shortcut for creating a user and granting rights at the same time. By splitting this command into `CREATE USER` and `GRANT` we make sure to support old and new versions.
> Docs: Replace GRANT + IDENTIFIED BY command incompatible with newer MySQL versions

- .github/workflows/integration-tests.yml
As those also implicitly test code in the icinga2 repo, it makes sense to run them periodically to notice if we break something over there.
(Some time at night was chosen by a fair dice roll.)
> Run daily integration tests

- tests/go.mod
- tests/go.sum
- tests/history_test.go
Tests for the following two PRs that extend the history integration tests so that they check if both icinga2 instances in a HA setup write identical history streams. Should only be merged after these are merged to prevent failing tests (d'oh!).
* https://github.com/Icinga/icinga2/pull/9112
* https://github.com/Icinga/icinga2/pull/9122
refs https://github.com/Icinga/icinga2/issues/9101
> Integration tests: test that both icinga2 instances write identical history streams

- .github/workflows/go.yml
not a hardcoded one.
This action takes care of that.
closes #428
> GHA: use latest staticcheck version

- pkg/config/config.go
- pkg/config/database.go
- pkg/config/redis.go
When embedding `TLS`, the field name is implicitly specified as `TLS`, which conflicts with the YAML key `tls`, which currently does not allow TLS to be enabled. I'm not entirely sure if this is a bug in goccy/go-yaml, but if a struct field name other than TLS is specified, the configuration works again.
> Fix currently not able to enable TLS

- doc/03-Configuration.md
Adds the `password` option to the description of how the Redis connection can be configured.
> doc: Document the password option for Redis

- tests/go.mod
- tests/go.sum
- tests/history_test.go
This PR fixes two causes of intermittent test failures:
1. In the TestHistory/HA test case, both nodes were started with the default `/etc/icinga2/conf.d/*.conf` still in place. This leads to an inconsistent configuration on both nodes which is doomed to write inconsistent history at some point. This will be fixed by https://github.com/Icinga/icinga-testing/pull/15 and this PR bumps the version of icinga-testing.
2. Running the sub-tests of TestHistory/HA in parallel can result in a situation where some history stream is checked for consistency while another sub-test is still running and generating events that also affect that stream (for example, the downtime test may generate notification, the notification test may generate state changes, ...) that are only processed by one of the nodes …
> Fix intermittent test failures

- schema/mysql/schema.sql
- schema/mysql/upgrades/1.0.0.sql
- schema/pgsql/schema.sql
To make custom variable searches case-insensitive by default.
fixes #443
> Schema: Make custom variable names case insensitive

- internal/command/command.go
Throwing a stacktrace at a user isn't the nicest thing to do (looks more like the application did something wrong rather than the user did something wrong).
Exit code 2 seems to be what go does when you panic it, but invalid config is somewhat similar to invalid cli options (which also uses exit code 2 at the moment), so I kept that one.
```
go run ./cmd/icingadb -c <(printf '{database: {type: invalid}}')
panic: invalid configuration: unknown database type "invalid", must be one of: "mysql", "pgsql"
goroutine 1 [running]:
github.com/icinga/icingadb/pkg/utils.Fatal(...)
/home/jbrost/dev/icingadb/pkg/utils/utils.go:114
github.com/icinga/icingadb/internal/command.New()
/home/jbrost/dev/icingadb/internal/command/command.go:41 +0x185
main.run()
/home/jbrost/dev/icingadb/cmd/icingadb/main.go:40 …
```
> Don't print a stacktrace on config errors

- .github/workflows/sql.yml
- cmd/icingadb/main.go
- config.yml.example
- doc/02-Installation.md
- doc/03-Configuration.md
- pkg/config/config.go
- pkg/config/history_retention.go
- pkg/icingadb/history/retention.go
- pkg/icingadb/history/sla.go
- pkg/icingadb/history/sync.go
- pkg/icingadb/v1/history/downtime.go
- pkg/icingadb/v1/history/state.go
- pkg/types/state_type.go
- schema/mysql/schema.sql
- schema/mysql/upgrades/1.0.0.sql
- schema/pgsql/schema.sql
- tests/cleanup_and_retention_test.go
- tests/go.mod
- tests/go.sum
- tests/internal/utils/database.go
- tests/sla_test.go
- tests/sql/main_test.go
- tests/sql/sla_test.go
This PR introduces special tables for recording data that is relevant for generating SLA reports:
* `sla_history_downtime`: One row for each downtime containing the actual start and end of the period in which the downtime was in effect.
* `sla_history_state`: One row for each hard state change.
These tables are filled in parallel to the corresponding history tables. There's also a SQL stored function giving an example implementation for computing SLA values with tests for this function in the Go code.
Having this data in tables separate from the full history tables allows this data to be kept for longer without storing the full history data for that longer period.
* https://github.com/Icinga/go-libs/pull/3
* https://github.com/Icinga/icinga-testing/pull/21
* …
> SLA reporting

- pkg/config/database.go
This PR implements two changes:
* PostgreSQL: also add the port number to the connection URI for Unix domain sockets as the port is also used to derive the full socket path (`/run/postgresql/.s.PGSQL.5432` for example).
* Make the `database`: `port` config field optional by using the default port. This is done in the connection code rather than using a `default` struct tag as the defaults are evaluated before the YAML is parsed so the database type is not known yet.
```console
$ go run ./cmd/icingadb -c <(printf '{database: {type: mysql, host: localhost}}')
2022-05-12T16:36:27.500+0200	INFO	icingadb	Starting Icinga DB
2022-05-12T16:36:27.500+0200	INFO	icingadb	Connecting to database
2022-05-12T16:36:27.501+0200	WARN	database	Can't connect to database. Retrying	{"error": "dial tcp …
```
> DB: use default ports and allow setting port for PostgreSQL Unix domain sockets

- pkg/icingadb/history/retention.go
Other components log this information periodically at level info, whereas the retention feature was completely quiet at that level. It's logged at the interval the retention cleanup is run rather than the global configured logging interval since retention cleanup is done less often.
Nothing logged at level info.
```
2022-05-11T09:30:08.862+0200	INFO	history-retention	Removed 5 old state history items
```
> Retention: periodically log number of items removed

- pkg/icingadb/cleanup.go
- pkg/icingadb/history/retention.go
This was added for the tests but the corresponding test was rewritten in #467 so it's no longer used or needed.
Also includes a small build fix for a conflict between #247 and #480 (I basically noticed the conflict while working on this PR before GitHub even sent me a mail for the failing actions, so I just fixed it here).
* #480: not really a functional dependency, but otherwise I'd remove the unused `rs` here just to add it again in the other PR.
> Retention: remove leftover code from older tests

- pkg/config/database.go
- pkg/config/redis.go
Starting Icinga DB with an empty config.
Tries to start, fails to connect, goes into retry mode, and finally fails with a long stack trace (see #472 for full output).
```console
$ go run ./cmd/icingadb -c <(printf '{}')
panic: invalid configuration: database host must be specified
goroutine 1 [running]:
github.com/icinga/icingadb/pkg/utils.Fatal(...)
/home/jbrost/dev/icingadb/pkg/utils/utils.go:114
github.com/icinga/icingadb/internal/command.New()
/home/jbrost/dev/icingadb/internal/command/command.go:41 +0x185
main.run()
/home/jbrost/dev/icingadb/cmd/icingadb/main.go:40 +0x57
main.main()
/home/jbrost/dev/icingadb/cmd/icingadb/main.go:36 +0x19
exit status 2
```
fixes #472
> Check for required database and Redis config options during config validation

- schema/pgsql/schema.sql
At the moment Icinga DB Web doesn't know the column types, so it sends
SQL queries with LIKE operators for all suggestions in the search bar,
which fails for numeric and enum types on PostgreSQL. To support this,
the LIKE operator (internally translated to ~~) is overloaded. Note
that this is only a temporary solution until Icinga DB Web provides
column type support.
> PostgreSQL: Support LIKE for integer/enum columns

- pkg/icingadb/cleanup.go
- pkg/icingadb/history/retention.go
- schema/pgsql/schema.sql
- tests/cleanup_and_retention_test.go
- tests/internal/utils/redis.go
This PR ensures that the retention feature only deletes history from the current environment. Previously, the deletion queries where missing an appropriate WHERE clause.
Also adds missing indices to the PostgreSQL schema. With this PR:
```console
$ diff -us <(grep -o 'idx_\w*' schema/mysql/schema.sql | sort -u) <(grep -o 'idx_\w*' schema/pgsql/schema.sql | sort -u)
Files /proc/self/fd/11 and /proc/self/fd/12 are identical
```
Indices are kept without the environment ID for now as icingadb-web currently does not support multiple environments so that feature is of limited use at the moment anyways and there will almost certainly be only one environment in the database. So adding the environment ID would only make the indices bigger until then and in one case would even require duplicating …
> Retention: take environment_id into account

- .github/workflows/integration-tests.yml
If I remember correctly, some time ago you were able to download artifacts from the job page, i.e. there was no issues with two jobs using the same artifact name within one workflow. Now it looks like you can only download the artifacts from the workflow page, so this commit allows you to download both files from there.
> Integration tests: use separate artifact names for MySQL/PostgreSQL

- pkg/com/bulker.go
instead of outputting zero values.
> oneBulk(): terminate once input closed (like the regular bulker)

- schema/mysql/schema.sql
- schema/mysql/upgrades/1.0.0.sql
- schema/pgsql/schema.sql
When UPSERT and DELETE statements are executed at the same time, a
deadlock can occur if both want to get an exclusive lock on one of the
PRIMARY KEY index pages. This happens with DELETE statements when there
is no suitable index for the columns used in the WHERE clause, which is
true for our history retention queries since commit https://github.com/Icinga/icingadb/commit/eccac78ff31186430a33d65d286eb91ad7d20d05. This PR
fixes the problem by adding a suitable index for the columns used in
these queries.
fixes #485
> Add environment_id to indices for history retention

- .github/workflows/go.yml
dependabot adds a link showing the diff of the dependency but when there are changes in indirect dependencies, these have to be diffed manually. This commit vendors the dependencies before and after a PR and outputs the diff.
This automates something I've been doing manually for dependabot PRs so far.
The PR currently includes a dependabot commit for testing/demonstrating the functionality. My suggestion for how to proceed:
1. Review/update PR until looking good.
2. Once reviewer(s) is (are) happy, I'll remove the dependabot commit leaving the other commit as is.
3. Final approval.
4. Merge.
> Show diff of dependencies in GitHub Actions

- tests/go.mod
- tests/go.sum
- tests/object_sync_test.go
This PR fixes tests for new icinga2 master versions.
A [recent change in icinga2](https://github.com/Icinga/icinga2/pull/9407) prevents modifying some object attributes via the API, most notably those that influence the name of the object. Previously, the tests would also include these attributes in the POST requests that modify the objects (but with the same value as before), something that is now rejected.  Therefore, this commits allows to label attributes as `nomodify` so that they won't be sent in this case.
The commit also bumps the Go standard version in the tests module to 1.18 to allow using generic functions from a newer version of `golang.org/x/exp`.
> Tests: don't update some attributes via API in to work with recent icinga2 changes

- pkg/common/sync_subject.go
- pkg/icingadb/sync.go
- pkg/icingadb/v1/entity.go
- pkg/icingaredis/client.go
Code comment TL;DR: Allocate the same amount of smaller data structures
* Before: 3.5G
* After: 2.8G
> Save memory during config sync via SyncSubject#FactoryForDelta()

- cmd/icingadb-migrate/convert.go
- cmd/icingadb-migrate/main.go
- cmd/icingadb-migrate/misc.go
- doc/06-Migration.md
for columns which are NULLable anyway.
> cmd/icingadb-migrate: avoid unnecessary config option

- doc/06-Migration.md
- doc/icingadb-migration.example.yml
1. Moves the example config to a separate file one can just download.
2. Establishes some kind of standard workflow for the migration.
> Improve documentation for migration tool

- doc/02-Installation.md
Apt-get has been deprecated for a while :)
> Replace apt-get with apt

- .github/workflows/go.yml
The jobs were failing and the output contained: "note: module requires Go 1.19" (e.g. https://github.com/Icinga/icingadb/actions/runs/4233417770/jobs/7354361633)
FYI: `^1.19` means `>= 1.19 && <2.0` (https://www.npmjs.com/package/semver#caret-ranges-123-025-004)
> GitHub Actions: run Go lint job with at least 1.19

- schema/mysql/schema.sql
- schema/mysql/upgrades/1.1.1.sql
- schema/pgsql/schema.sql
- schema/pgsql/upgrades/1.1.1.sql
fixes #579
Tested fresh and upgraded schema on both RDBMSes.
> schema: notification: enlarge name and name_ci 255 -> 767

- pkg/retry/retry.go
During connect(2) we may get ECONNREFUSED between server's bind(2) and listen(2), but the most downtime between boot and service start the socket won't exist, yet. I.e. ENOENT is the de facto ECONNREFUSED of *nix sockets.
Tested this new commit vs. its parent commit. Test case - see:
fixes #543
> retry.Retryable(): treat ENOENT (AF_UNIX) like ECONNREFUSED, i.e. also retry

- pkg/icingaredis/heartbeat.go
> Heartbeat#sendEvent(m): nil-check m before dereferencing it

- tests/go.mod
- tests/go.sum
As a security fix, Go implemented stricter checks for the Host header in the http package. This [breaks the Go Docker client library](https://github.com/moby/moby/issues/45935) resulting in "http: invalid Host header" errors in our integration tests.
A [fix](https://github.com/moby/moby/pull/45942) was merged to the 24.0 branch, but is not yet included in a release. Therefore, this commit updates the dependency to a specific commit (`go get -u github.com/docker/docker@24.0`). Once it's included in a release, this can be switched back to using a release version.
Example of a currently failing pipeline: https://github.com/Icinga/icingadb/actions/runs/5640729645/job/15277750971
> Make integration tests work with Go 1.20.6

- pkg/types/binary.go
- pkg/types/binary_test.go
- pkg/types/bool.go
- pkg/types/bool_test.go
- pkg/types/unix_milli.go
- pkg/types/unix_milli_test.go
> {Bool,Binary,UnixMilli}#MarshalJSON(): return valid JSON, not empty string

- cmd/icingadb-migrate/main.go
- pkg/config/config.go
- pkg/config/config_test.go
Useful against config validation or runtime failures caused by wrong field spelling or YAML indentation.
```
➜  icingadb git:(yaml.DisallowUnknownField) ✗ go run ./cmd/icingadb-migrate -c i2i.yml -t `mktemp -d`
can't parse config file: [1:1] unknown field "Icinga2"
>  1 | Icinga2:
^
2 |   env: da39a3ee5e6b4b0d3255bfef95601890afd80709
3 | ido:
4 |   type: mysql
5 |
exit status 2
```
refs #574
> Config parsing: fail on unknown fields and print them

- pkg/flatten/flatten.go
- pkg/icingadb/v1/customvar.go
- schema/mysql/schema.sql
- schema/mysql/upgrades/1.2.0.sql
- schema/pgsql/schema.sql
- schema/pgsql/upgrades/1.2.0.sql
- tests/object_sync_test.go
Just inserts empty custom vars of type `array` & `map` with `NULL` value in to the `customvar_flat` table.
fixes #597
> Write a hint for empty arrays/dicts into `customvar_flat`

- cmd/icingadb-migrate/convert.go
i.e. ignore such rows.
This is the ~best~ only thing we can do here.
> icingadb-migrate: handle NULL event time columns

- pkg/icingadb/db.go
- pkg/icingadb/ha.go
- pkg/retry/retry.go
so that connection attempts will also be re-tried on RDBMS-specific errors, e.g. Postgres' 57P03 (the database system is starting up), not to crash. On the other hand, SQL operations which are safe to retry on SQL errors are also safe to retry on network errors.
fixes #561
https://github.com/Icinga/icingadb/issues/561#issuecomment-1564120245
```
2023-05-26T12:19:58.736+0200	INFO	icingadb	Starting Icinga DB
2023-05-26T12:19:58.736+0200	INFO	icingadb	Connecting to database at 'localhost:2345'
2023-05-26T12:20:01.610+0200	WARN	database	Can't connect to database. Retrying	{"error": "pq: the database system is starting up"}
2023-05-26T12:20:08.612+0200	INFO	database	Reconnected to database{"after": "9.87615987s", "attempts": 4}
2023-05-26T12:20:08.620+0200	FATAL	icingadb	pq: relation …
```
> Merge network and database error retryability detection functions

- cmd/icingadb-migrate/convert.go
- cmd/icingadb-migrate/embed/downtime_query.sql
Such appear e.g. for scheduled but never triggered flexible Downtimes. Not triggered = no events.
In addition this
fixes #621
for reasons Julian described in https://github.com/Icinga/icingadb/pull/622#pullrequestreview-1550032165. (I tested that.)
> cmd/icingadb-migrate: ignore icinga_downtimehistory#was_started=0 rows

- pkg/icingadb/ha.go
The RDBMS rejects them by default. But it doesn't rejects their equivalent: Append "LOCK IN SHARE MODE" to every SELECT in a REPEATABLE READ transaction. Now we do the latter with MySQL.
fixes #576
```
root@aklimov-pxc:~# cat idb.yml
database:
type: mysql
host: 172.19.0.3
database: icingadb
user: icingadb
password: icingadb
redis:
host: localhost
port: 6379
root@aklimov-pxc:~# /home/debian/l63 -c idb.yml
2023-06-22T13:12:07.566Z	INFO	l63	Starting Icinga DB
2023-06-22T13:12:07.566Z	INFO	l63	Connecting to database at '172.19.0.3:0'
2023-06-22T13:12:07.579Z	INFO	l63	Connecting to Redis at 'localhost:6379'
2023-06-22T13:12:07.580Z	INFO	l63	Starting history sync
2023-06-22T13:12:08.282Z	INFO	heartbeat	Received Icinga heartbeat	{"environment": "79c4cbeb3eb06a9bfd91beeb60a8ea842234a96d"} …
```
> Support Percona XtraDB Cluster by not using SERIALIZABLE transactions directly

- cmd/icingadb-migrate/convert.go
- cmd/icingadb-migrate/main.go
- cmd/icingadb-migrate/misc.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
Don't INSERT IGNORE everything, then UPSERT everything. Instead INSERT IGNORE    flapping_history, UPSERT flapping_history and finally INSERT IGNORE history.
> convertFlappingRows(): fix foreign key error history -> flapping_history

- schema/mysql/schema.sql
- schema/mysql/upgrades/1.2.0.sql
- schema/pgsql/schema.sql
- schema/pgsql/upgrades/1.2.0.sql
resolves #523
postgres changes still tbd
> schema: Add new index for `customvar_flat`

- schema/mysql/schema.sql
- schema/mysql/upgrades/1.2.0.sql
- schema/pgsql/schema.sql
- schema/pgsql/upgrades/1.2.0.sql
These new indices make these tables consistent with `usergroup`.
fixes #615
> schema: Add missing indices to `hostgroup` and `servicegroup`

- .github/workflows/compliance.yml
- .github/workflows/go.yml
- .github/workflows/integration-tests.yml
- .github/workflows/sql.yml
- .github/workflows/version.yml
- pkg/icingadb/v1/environment.go
- pkg/utils/utils.go
- pkg/version/version.go
There was a mix of diferent action and Go versions specified throughout the GitHub Actions workflow configs. In general, we want to be compatible with the latest Go 1.x version, so just specify that instead of bumping versions everywhere when necessary.
At the same time, bump the actions/setup-go to v4, the latest currently available version. This prefers versions already cached on the runner and enables automatic caching for dependencies.
Also requires some reformatting of comments, looks like `go fmt` likes indentation within comments to look differently now.
The main motivation for this change is to allow upgrading go.uber.org/zap from 1.24.0 to 1.25.0 which no longer works with Go 1.18 (see #632).
> GitHub Actions: use actions/setup-go@v4 and go-version: 1.x

- schema/mysql/schema.sql
- schema/mysql/upgrades/1.2.0.sql
- schema/pgsql/schema.sql
- schema/pgsql/upgrades/1.2.0.sql
This improves the resulting sort order when `ORDER BY event_time, event_type` is used. `state_change` comes first as it can cause many of the other events like trigger downtimes, remove acknowledgements and send notifications. Similarly, `notification` comes last as any other event can result in a notification. This will result in history events for scenarios like state changes, triggers downtime, sends downtime start notification being sorted in that order.
Apart from that, end events sort before the corresponding start events as any ack/comment/downtime/flapping period should last for more than a millisecond, therefore if there should be two events within the same millisecond, the end event corresponds to the older period and is sorted first. The remaining order is by impact and cause, …
> Schema: change sort order of history event type enum

- .github/workflows/compliance.yml
- .github/workflows/docker.yml
- .github/workflows/go.yml
- .github/workflows/integration-tests.yml
- .github/workflows/sql.yml
- .github/workflows/version.yml
The branch was renamed, the same change has to be done in the GitHub Actions config so that the workflow continue to run.
> GitHub Actions: change master to main

- AUTHORS
- CHANGELOG.md
- doc/04-Upgrading.md
- internal/version.go
Includes version bump, changelog and upgrading docs.
Remaining other PRs to be merged for the release:
* #631: already included in the changelog.
* #634: GitHub Actions only, not relevant for changelog.
> Release 1.1.1

- .github/workflows/compliance.yml
- .github/workflows/docker.yml
- .github/workflows/go.yml
- .github/workflows/integration-tests.yml
- .github/workflows/sql.yml
- .github/workflows/version.yml
Merge into `main` to get GitHub Actions in support branches that will be created in the future.
refs #635 (same PR into `support/1.1`)
> GitHub Actions: also run on support branches

- doc/04-Upgrading.md
Looks like these were never in /usr/share/doc and the documentation was just wrong for 1.0.0.
The updated paths match both 1.0.0 release packages and the current snapshot packages:
```console
$ curl -s https://packages.icinga.com/debian/pool/main/i/icingadb/icingadb_1.0.0-1.bullseye_amd64.deb | dpkg --contents - |& grep -F .sql        
-rw-r--r-- root/root     59172 2022-06-29 19:33 ./usr/share/icingadb/schema/mysql/schema.sql
-rw-r--r-- root/root     28474 2022-06-29 19:33 ./usr/share/icingadb/schema/mysql/upgrades/1.0.0-rc2.sql
-rw-r--r-- root/root     12098 2022-06-29 19:33 ./usr/share/icingadb/schema/mysql/upgrades/1.0.0.sql
-rw-r--r-- root/root     93974 2022-06-29 19:33 ./usr/share/icingadb/schema/pgsql/schema.sql
```
```console
$ curl -s …
```
> doc/04-Upgrading.md: Fix path for schema upgrades

- cmd/icingadb/main.go
To better recognize the Icinga DB version used in case of errors, it is now logged at startup.
If VCS is available during build, the current commit is included.
- Dirty VCS directory:
> 2024-03-11T14:36:29.317+0100    INFO    icingadb        Starting Icinga DB daemon (1.1.1-g0e9810c-dirty)
- Clean VCS directory:
> 2024-03-11T14:38:09.664+0100    INFO    icingadb        Starting Icinga DB daemon (1.1.1-geed8589)
- Build with `-buildvcs=false`:
> 2024-03-11T14:38:56.554+0100    INFO    icingadb        Starting Icinga DB daemon (1.1.1)
Closes #689.
> cmd/icingadb: Log Icinga DB version during startup

- tests/history_bench_test.go
- tests/history_test.go
- tests/sla_test.go
Some test cases always used a MySQL database as they didn't use the proper function which would respect the `ICINGADB_TESTS_DATABASE_TYPE=pgsql` environment variable. This commit fixes this and updates a similarly left-over error message as well.
Excerpts from the GitHub Actions job artifacts (`xzgrep -E 'created (mysql|postgresql) container'`):
https://github.com/Icinga/icingadb/actions/runs/8324491540
:heavy_check_mark:  No problem, creates only a MySQL container as expected:
```
{"L":"DEBUG","T":"2024-03-18T09:52:05.779Z","M":"created mysql container","mysql":true,"container-name":"icinga-testing-62f6a821-mysql","container-id":"567aae686d80883b356a20e7340e553a3f97a8c87a94819a0af242f5ac8c7367"}
```
:x:  Unexpectedly creates a MySQL container in addition to the expected PostgreSQL …
> Integration tests: don't hard-code MySQL in some tests

- pkg/config/database.go
For MySQL (and MariaDB, etc.), in addition to `ANSI_QUOTES` SQL mode, we now also set `TRADITIONAL`, which enables strict mode.
fixes #611
refs #624
> MySQL/MariaDB: Use strict SQL mode

- pkg/driver/driver.go
which just wraps a method with equal signature.
> Remove redundant closure

- schema/pgsql/schema.sql
- schema/pgsql/upgrades/1.1.2.sql
- tests/sql/sla_test.go
The final division within the `get_sla_ok_percent` SQL function in its PostgreSQL implementation silently truncated decimal places. An explicit decimal cast resulted for this equation resulted in a decimal value.
To both verify and catch this in the future, a test with odd numbers was added. This already succeeded for MySQL, but needed the modified schema for PostgreSQL.
- Test against the old schema:
```
+ ICINGADB_TESTS_DATABASE_TYPE=mysql
+ ICINGA_TESTING_ICINGADB_BINARY=[...]/git/github.com/Icinga/icingadb/icingadb
+ ICINGA_TESTING_ICINGADB_SCHEMA_MYSQL=[...]/git/github.com/Icinga/icingadb/schema/mysql/schema.sql
+ ICINGA_TESTING_ICINGADB_SCHEMA_PGSQL=[...]/git/github.com/Icinga/icingadb/schema/pgsql/schema.sql
+ ./icingadb-test -icingatesting.debuglog debug.log -test.v -test.run …
```
> PostgreSQL: get_sla_ok_percent to return decimal

- schema/mysql/schema.sql
- schema/mysql/upgrades/1.0.0-rc2.sql
- schema/mysql/upgrades/1.0.0.sql
- schema/mysql/upgrades/1.1.1.sql
- schema/mysql/upgrades/1.1.2.sql
We previously incorrectly used `CURRENT_TIMESTAMP()` an alias for `NOW()` which returns the current date and time in the format `YYYY-MM-DD hh:mm:ss` using the session time zone. Since we are using numeric context, the value is stored in the format `YYYYMMDDhhmmss`. But actually we want to set a (millisecond) UNIX timestamp here, so we need to use `UNIX_TIMESTAMP()` instead.
Since the timestamps need to be corrected, there is also a schema upgrade.
> MySQL/MariaDB: Fix `icingadb_schema.timestamp` not being UNX time

- cmd/icingadb-migrate/convert.go
- pkg/flatten/flatten.go
- pkg/flatten/flatten_test.go
- pkg/icingadb/ha.go
- pkg/types/string.go
E.g. 2000000000000000000 (explicitly), not 2e+18 (as with fmt.Sprintf("%v")).
fixes Icinga/icingadb#659
> Flatten(): render even large numbers as-is, not using scientific notation

- config.example.yml
- doc/03-Configuration.md
> Document `retention.count` & `retention.interval` options

- config.example.yml
- doc/03-Configuration.md
These options are user configurable but are not yet documented anywhere visible to the end user. This PR should hopefully spare us future questions like *how many connections Icinga DB is allowed to open?* or *Icinga DB opens abnormally too many connections to the database?*. Yes, these questions are serious and were also asked by our support customers.
> Document `database.options` properly

- pkg/icingadb/history/sync.go
```diff
diff --git a/pkg/icingadb/history/sync.go b/pkg/icingadb/history/sync.go
index 4be0e71..fb31d31 100644
--- a/pkg/icingadb/history/sync.go
+++ b/pkg/icingadb/history/sync.go
@@ -140,7 +140,9 @@ func (s Sync) deleteFromRedis(ctx context.Context, key string, input <-chan redi
}
}).Stop()
-       bulks := com.Bulk(ctx, input, s.redis.Options.HScanCount, com.NeverSplit[redis.XMessage])
+       justKidding := make(chan redis.XMessage)
+       close(justKidding)
+       bulks := com.Bulk(ctx, justKidding, s.redis.Options.HScanCount, com.NeverSplit[redis.XMessage])
stream := "icinga:history:stream:" + key
for {
select {
```
&#x2193;
```go
2024-03-28T15:00:22.430+0100    FATAL   main    ERR wrong number of arguments for 'xdel' command
can't perform "[xdel icinga:history:stream:flapping]" …
```
> `history.Sync`: Don't operate on closed channel

- cmd/icingadb/main.go
- pkg/icingadb/ha.go
- pkg/icingaredis/heartbeat.go
The reason for a switch in the HA roles was not always directly clear. This change now introduces additional logging, indicating the reasoning for either taking over or handing over the HA responsibility.
Next to additional logging messages, both the takeover and handover channel are now transporting a string to communicate the reason instead of an empty struct{}. By doing so, both the "Taking over" and "Handing over" log messages are enriched with a reason.
This also required a change in the suppressed logging handling of the HA.realize method, which got its logging enabled through the shouldLog parameter. Now, there are both recurring events, which might be suppressed, as well as state changing events, which should be logged. Therefore, and because the logTicker's functionality was not …
> Enhance HA "Taking over", "Handing over" logging

- cmd/icingadb-migrate/convert.go
- doc/04-Upgrading.md
- pkg/icingadb/db.go
- pkg/icingadb/v1/checkable.go
- pkg/icingadb/v1/history/state.go
- pkg/icingadb/v1/state.go
- schema/mysql/schema.sql
- schema/mysql/upgrades/1.1.2.sql
- schema/mysql/upgrades/optional/1.1.2-history.sql
- schema/pgsql/schema.sql
- schema/pgsql/upgrades/1.1.2.sql
- schema/pgsql/upgrades/optional/1.1.2-history.sql
A float isn't necessary as in Icinga 2 Checkable#max_check_attempts and check_attempt are ints. But uint8 isn't enough for e.g. 1 check/s to get HARD after 5m (300s > 255).
> Unify check attempt data type to uint32 already used somewhere

- pkg/config/database.go
**Before:**
```bash
2024-04-08T13:55:58.621+0200    WARN    database        Can't connect to database. Retrying     {"error": "driver: bad connection"}
2024-04-08T13:56:00.294+0200    WARN    database        Can't connect to database. Retrying     {"error": "dial tcp [::1]:3306: connect: connection refused"}
2024-04-08T13:56:40.352+0200    INFO    database        Reconnected to database {"after": "41.737475334s", "attempts": 10}
[mysql] 2024/04/08 14:03:19 connection.go:49: closing bad idle connection: EOF
[mysql] 2024/04/08 14:03:19 connection.go:49: closing bad idle connection: EOF
```
**After:**
```bash
2024-04-08T14:41:53.032+0200    DEBUG   database        [unexpected EOF]
2024-04-08T14:41:53.272+0200    DEBUG   database        [unexpected EOF]
2024-04-08T14:41:53.272+0200    WARN …
```
> Register mysql default logger prior to `mysql#NewConfig()`

- pkg/config/config.go
- pkg/icingadb/objectpacker/objectpacker.go
- tests/history_test.go
The io/ioutil package is deprecated since Go 1.16. All its functions were moved to either the io or os package.
> Remove deprecated io/ioutil package references

- pkg/retry/retry.go
Otherwise, Icinga DB will crash immediately!
```bash
2024-04-11T09:08:45.502+0200    INFO    history-sync    Synced 104 notification history items
2024-04-11T09:08:47.806+0200    WARN    database        Can't connect to database. Retrying     {"error": "pq: the database system is shutting down"}
2024-04-11T09:08:47.895+0200    WARN    database        Can't connect to database. Retrying     {"error": "read tcp 127.0.0.1:53259->127.0.0.1:5432: read: connection reset by peer"}
2024-04-11T09:08:48.095+0200    WARN    database        Can't connect to database. Retrying     {"error": "read tcp 127.0.0.1:53260->127.0.0.1:5432: read: connection reset by peer"}
2024-04-11T09:08:48.236+0200    FATAL   main    EOF
can't retry
github.com/icinga/icingadb/pkg/retry.WithBackoff …
```
> Retry `io.EOF` error

- pkg/icingadb/driver.go
The additional check against a `driver.ErrBadConn` is now also part of `retry.Retryable`. Thus, it can be dropped.
References https://github.com/Icinga/icingadb/pull/740#issuecomment-2049236759
> icingadb: Remove shouldRetry

- pkg/icingadb/db.go
During testing, I just encountered a race condition where my Galera cluster was not yet ready, causing the initial schema check to fail.
```
2024-04-11T08:13:40.401Z        INFO    icingadb        Starting Icinga DB daemon (1.1.1)
2024-04-11T08:13:40.401Z        INFO    icingadb        Connecting to database at 'mysql:3306'
2024-04-11T08:13:40.404Z        FATAL   icingadb        Error 1047 (08S01): WSREP has not yet prepared node for application use
can't check database schema version
github.com/icinga/icingadb/pkg/icingadb.(*DB).CheckSchema
/go/src/github.com/Icinga/icingadb/pkg/icingadb/db.go:115
main.run
/go/src/github.com/Icinga/icingadb/cmd/icingadb/main.go:74
main.main
/go/src/github.com/Icinga/icingadb/cmd/icingadb/main.go:37
runtime.main
/usr/local/go/src/runtime/proc.go:271 …
```
> icingadb.DB: Retry Schema Checks

- pkg/backoff/backoff.go
- pkg/icingadb/driver.go
- pkg/icingadb/ha.go
- pkg/icingaredis/heartbeat.go
Merge after #698 because of https://github.com/Icinga/icingadb/pull/738#issuecomment-2049074001.
> Unify notation of `n * time.Duration`

- cmd/icingadb-migrate/main.go
```
bad env ID: must be 20 bytes long, has 21 bytes
```
👍
> cmd/icingadb-migrate: replace magic number 20 with sha1.Size

- cmd/icingadb-migrate/main.go
An env ID with the wrong length, either due to a copy-paste error or human error during testing, results in a SQL CHECK CONSTRAINT violation that is retried multiple times until it finally fails.
> icingadb-migrate: Verify env ID length

- doc/02-Installation.md
The anchor contains web, which is incorrect in this context.
> doc/02-Installation.md: Fix installing-icingadb-db-packages anchor

- cmd/icingadb-migrate/embed/comment_query.sql
- cmd/icingadb-migrate/embed/downtime_query.sql
Historical data from an older Icinga 2 installation contained NULL values for the name column in some rows of the icinga_commenthistory and icinga_downtimehistory tables.
Normally this field contains something like
${name1}!${name2}!${unique_value} where the $unique_value is based on a timestamp for older entries and a UUID for newer ones. For a concrete example, this could be "host.example.com!ping6!123…".
Unfortunately, using an empty string for these NULL values will cause an error later because the new primary key will be calculated based on it. Therefore, a new deterministic name is generated based on the primary keys and the known name1 and name2 values.
Closes #766.
> icingadb-migrate: Mitigate NULL names in {comment,downtime}_query

- .github/dependabot.yml
Dependabot supports to automatically refresh GitHub actions as well, so we should use it to avoid such errors:
https://github.com/Icinga/icingadb/actions/runs/10903916830/job/30259089610
> Update GHA dependencies via dependabot

- pkg/icingadb/types/comment_type.go
by just calling CommentType#UnmarshalJSON().    The implementations behave identically. (Just like for AcknowledgementState,    NotificationStates, NotificationTypes and StateType.)
> Shorten CommentType#UnmarshalText()

- pkg/icingaredis/utils.go
A `for x := range c` will block as long as c blocks, ignoring `<-ctx.Done()`. The latter has to be checked via `select` instead, together with c.
* Discovered during a discussion about the unit tests: https://github.com/Icinga/icingadb/pull/799#issuecomment-2355907794
Also, _hide whitespace_ under _files changed_ is your friend. 😅
> pkg/icingaredis/: check context termination while looping over channel

- internal/config/config.go
- pkg/icingadb/history/retention.go
As discussed in #821, allowing huge retention values - as the type uint64 allows - may result in overflows. Especially Go's time.AddDate() method silently overflows for huge values, resulting in unexpected comparison times.
> $ ./icingadb --config <(echo 'retention: {history-days: -1}')
> can't parse YAML file /proc/self/fd/11: cannot unmarshal -1 into Go value of type uint16 ( overflow )
>
> $ ./icingadb --config <(echo 'retention: {history-days: 100000}')
> can't parse YAML file /proc/self/fd/11: cannot unmarshal 100000 into Go value of type uint16 ( overflow )
> RetentionConfig: restrict days to uint16

- .github/workflows/go.yml
- cmd/icingadb-migrate/convert.go
- cmd/icingadb-migrate/main.go
- cmd/icingadb-migrate/misc.go
- cmd/icingadb/main.go
- pkg/icingadb/cleanup.go
- pkg/icingadb/delta_test.go
- pkg/icingadb/types/notification_type.go
First, the same GitHub Action used in the icinga-go-library was added to the Go workflow.
Then, the findings were addressed. In general, these were mostly missing return check - when being unused anyway -, potential overflows for integer type conversions, and SHA1 warnings.
If applicable, the code was slightly modified to perform the necessary checks. Sometimes the linter has detected the checks. Sometimes not and a linter comment was added.
> Introduce golangci-lint and fix findings

- pkg/icingadb/runtime_updates.go
This enforces which side (caller/function) can read and especially    close/write to a particular channel at compile time.    That leaves less room for bugs (which had to be detected by tests otherwise).
> Make structifyStream() channel types more explicit, e.g. input only

- cmd/icingadb/main.go
- pkg/icingadb/ha.go
- pkg/icingaredis/telemetry/heartbeat.go
Go 1.19 introduced `sync/atomic#Pointer` among other things, so we no longer need to use the Atomic wrapper from our Icinga Go library.
> Use `sync/atomic#Pointer` instead of our own wrapper

- cmd/icingadb/main.go
- pkg/icingaredis/heartbeat.go
- pkg/icingaredis/telemetry/heartbeat.go
Instead of declaring a field as `int64` and using helper functions for atomic operations, it is better and recommended to use the new atomic types like `atomic.Int64`.
> Replace `int64` with `atomic.Int64` where applicable

- doc/02-Installation.md
- doc/02-Installation.md.d/01-Amazon-Linux.md
- doc/02-Installation.md.d/02-CentOS.md
- doc/02-Installation.md.d/03-Debian.md
- doc/02-Installation.md.d/04-RHEL.md
- doc/02-Installation.md.d/05-SLES.md
- doc/02-Installation.md.d/06-Ubuntu.md
- doc/02-Installation.md.d/From-Source.md
- doc/03-Configuration.md
* Removes the package installation steps for the different operating systems to
have them injected centrally by our icinga.com documentation tools instead,
while maintaining readability and comprehensibility on GitHub and other
viewers.
* Adds `From Source` section to installation docs.
closes #818
> Adjust installation docs for centralized icinga.com doc injection

- schema/mysql/upgrades/1.3.0.sql
PR #792 mistakenly added a `NOT NULL` clause to a nullable columns. This PR corrects that by dropping that clause and adding a `DEFAULT NULL` clause, making it consistent the actual schema file.
fixes #855
> schema: Fix broken upgrade script `1.3.0`

- cmd/icingadb/main.go
- pkg/icingadb/ha.go
- pkg/icingaredis/heartbeat.go
- **icingadb: Unify select cases for derived contexts**
The main loop select cases for hactx.Done() and ctx.Done() were unified, as hactx is a derived ctx. A closed ctx case may be lost as the hactx case could have been chosen.
- **HA: Increase log level for heartbeats from the future**
Timing issues may be the root of future failures. Thus, it is important to be aware if the timing seems to be out of sync.
- **HA: Deferred SQL Transaction Rollback**
Each transaction is created within the retryable function, but this function may be exited prematurely before committing. A deferred rollback ensures that the transaction will be rolled back and cleaned up in this case, or will be a noop when performed after the commit.
- **HA: Insert environment within retryable function**
The …
> Abort HA Realization Logic After Timeout

- pkg/icingadb/ha.go
In theory, this should not happen. This assumption is based on the trust in the database transaction performing the HA realization logic. However, one debugged log let one assume that this happened anyway.
This change mostly signals an error while also explicitly giving up the HA state. Doing so should at least alarm a person reading the logs.
---
ref/IP/55850
> HA State: ensure not this and another instance can be responsible

- tests/history_test.go
While debugging a totally unrelated issue, I stumbled over the following PostgreSQL output:
```
[97] ERROR:  syntax error at or near "ORDER" at character 173
[97] STATEMENT:  SELECT h.event_time, h.event_type FROM history h
JOIN host ON host.id = h.host_id
LEFT JOIN downtime_history d ON d.downtime_id = h.downtime_history_id
WHERE host.name = ?
ORDER BY h.event_time
```
The relevant code misses a db.Rebind as the "?" character is for MySQL.
> test: Rebind Log Output Query for PostgreSQL

- config.example.yml
- doc/03-Configuration.md
As icinga-go-library v0.4.0 supports these now, it should be documented in Icinga DB.
Closes #782.
---
Requires the icinga-go-library version 0.4.0 release first, #877.
> Docs: Redis ACL Username and Database

- cmd/icingadb/main.go
Previously, the HA feature was allowed to open `max_connections` database connection in parallel to other Icinga DB components. Meaning, Icinga DB wasn't limited to the configured `max_connections`, but effectively to `2 * max_connections`.
> HA: Limit max open database connections to `1`

- cmd/icingadb/main.go
- internal/config/config.go
- pkg/icingadb/schema.go
To get rid of docker-icingadb and its additional entry point, the schema import functionality has been implemented directly in Icinga DB. Using the new `--database-auto-import` command line argument will result in an automatic schema import if no schema is found.
The implementation is split between the already existing `CheckSchema` function and the introduced `ImportSchema` function.
The `CheckSchema` function is now able to distinguish between the absence of a schema and an incorrect schema version. Both situations return a separate error type.
As before, `CheckSchema` is called in the `main` function. If the error type now implies the absence of a schema (`ErrSchemaNotExists`) and the `--database-auto-import` flag is set, the auto-import is started.
The schema import itself is …
> Auto Import Database Schema

- cmd/icingadb-migrate/embed/comment_query.sql
- cmd/icingadb-migrate/embed/downtime_query.sql
- cmd/icingadb-migrate/embed/flapping_query.sql
- cmd/icingadb-migrate/embed/notification_query.sql
- cmd/icingadb-migrate/embed/state_query.sql
By introducing an explicit "AS" to set output names in the SELECT column list, there are no issues with reserved names. Unfortunately, this happened on PostgreSQL in the older version 13 with the reserved name "name". Adding "AS" mitigates this issue.
Furthermore, I have put each column name in its own line for the SELECT queries to ease the readability of the query itself and of future diffs.
Fixes #884.
> icingadb-migrate: Explicit AS in SELECT

- Containerfile
This caches more layers users don't have to download.
> Containerfile: order layers by how likely they change over time

- .github/workflows/container-image.yml
`latest` is currently tagged for all pushes to the `main` branch:
https://hub.docker.com/r/icinga/icingadb/tags
> `container-image` workflow: Tag `latest` only on release

- .github/workflows/container-image.yml
Without further investigation, this only seems to push the image with the digest as a tag, which only pollutes the registry.
> `container-image` workflow: Don't push attestations to image registries

- .github/workflows/container-image.yml
To ensure the workflow is reusable across our repositories, it must support releasing from different release trains, such as when issuing bugfix or security releases for older versions alongside newer ones. This change introduces custom logic to 
determine when to apply the latest tag and major version tags. The docker/metadata-action unconditionally applies these tags, which could override existing greater tags. The new logic compares the current release tag against all existing tags using semantic versioning rules, a feature not inherently provided by docker/metadata-action.
You can check the changes in this repo:
https://github.com/lippserd/container-image-workflow-test/pkgs/container/container-image-workflow-test
Supersedes: #915
> `container-image` workflow: Tag latest/major version only when applicable

- Containerfile
This sets the PATH environment variable so that the binary installed to the container image can be found by just its name. This makes it nicer to manually provide a command by the container, so for example, now "docker run --rm -it icinga/icingadb:dev icingadb --version" works. The binary is still installed under the same path, so it can still be invoked using the same absolute path as before.
```
$ docker run --rm -it icinga/icingadb:dev icingadb --version 
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "icingadb": executable file not found in $PATH
Run 'docker run --help' for more information
$ docker run --rm -it …
```
> Containerfile: allow running the binary without absolute path

- .github/workflows/go.yml
- go.mod
go.mod: Bump go version to 1.24.1
Recently the dependabot PRs would otherwise add the toolchain directive.
GHA: Remove staticheck action from Go Workflow
After bumping the Go version to 1.24.1, the staticcheck-action fails
since it is outdated. No update is available. However, since staticcheck
is enabled by default in the golangci-lint action, it can be removed.
> go.mod: Bump go version to 1.24.1

- cmd/icingadb/main.go
Based on the configured log level, some useful log messages will be discarded. While this works as intended, this will result in unbalanced logs - HA hand over is logged, taking over is not - or missing version strings useful for log analysis.
Fixes #918
> Always log certain HA and Startup Messages

- doc/01-About.md
- doc/03-Configuration.md
- doc/07-Operations.md
doc/01-About.md: Big Picture
Inspired by the "Big Picture" section in the Icinga Notifications
documentation[^0], such a section was introduced for Icinga DB as well.
It aims to describe the essential components in an Icinga DB setup along
the architecture diagram for novice users. This hopefully helps new
users to understand what Icinga DB actually is and how it interconnects.
[^0]: https://icinga.com/docs/icinga-notifications/latest/#big-picture
---
doc/03-Configuration.md: Mention forced log events
The logging was slightly modified in #920, resulting in a few log
messages being shown regardless of the user configured log level. Since
this may not be the expected behavior, it is now mentioned in the docs.
---
doc/07-Operations.md: New Operations section
The newly introduced Operations …
> Doc: Big Picture Overview, Forced Logs, Operations

- pkg/icingadb/cleanup.go
- pkg/icingadb/history/retention.go
Speed up history retention by deleting old rows in an unordered fashion.
History retention deletes all rows in the history table if their timestamp is older than the configured retention period. This deletion is performed in bulk, typically limiting each statement to 5,000 entries. After the final iteration, all older entries are deleted.
So far, the deletion queries required an order for the deletion process to start with the oldest rows. If the tables to be cleaned were huge, ordering the data would be expensive. However, since all old data will be deleted without further delay, deleting the data in order is unnecessary.
For reference, compare the two following execution plans generated by PostgreSQL for a state_history table of round about 32k entries.
```
icingadb=> EXPLAIN SELECT id …
```
> Retention: Unordered deletion in CleanupStmt

- pkg/icingadb/ha.go
- pkg/icingadb/v1/icingadb_instance.go
- schema/mysql/schema.sql
- schema/mysql/upgrades/1.4.0.sql
- schema/pgsql/schema.sql
- schema/pgsql/upgrades/1.4.0.sql
Store the current Icinga DB version in the icingadb_instance table to be shown in Icinga DB Web's health view.
Fixes #962.
---
@nilmerg: This would be a very straight forward solution, adding a `icingadb_version` column to be populated by Icinga DB. Thus, the Icinga DB version would be stored next to the Icinga 2 version. Does this work for Web?
> Add icingadb_version column to icingadb_instance

- pkg/icingadb/cleanup.go
- pkg/icingadb/ha.go
- pkg/icingadb/schema.go
Replace a custom backoff duration with backoff.DefaultBackoff introduced in the last IGL update[^0].
This was done for each occurrence except the one within the HA code, where a comment was added stating the reason. Since the HA.realize() method is bound by its context's deadline, introducing unnecessary delay may harm.
Fixes #965.
[^0]: https://github.com/Icinga/icinga-go-library/pull/133
> pkg/icingadb: Use backoff.DefaultBackoff

- doc/04-Upgrading.md
A new section on how to actually apply the database schema upgrade was introduced. This new section should take a user's fear to mess up a schema upgrade.
Fixes #926.
> docs/04-Upgrading.md: Database Schema Upgrades

- cmd/icingadb-migrate/cache.go
- cmd/icingadb-migrate/convert.go
- cmd/icingadb-migrate/main.go
- cmd/icingadb-migrate/misc.go
- cmd/icingadb/main.go
- pkg/icingadb/delta_test.go
- pkg/icingadb/entitiesbyid.go
- pkg/icingadb/entitiesbyid_test.go
- pkg/icingadb/history/retention.go
- pkg/icingadb/history/sync.go
- pkg/icingadb/overdue/sync.go
- pkg/icingadb/runtime_updates.go
- pkg/icingadb/scoped_entity.go
- pkg/icingadb/v1/customvar.go
- pkg/icingadb/v1/history/ack.go
- pkg/icingadb/v1/history/comment.go
- pkg/icingadb/v1/history/downtime.go
- pkg/icingadb/v1/history/flapping.go
- pkg/icingadb/v1/history/meta.go
- pkg/icingadb/v1/history/notification.go
- pkg/icingaredis/utils.go
- pkg/icingaredis/utils_test.go
- pkg/icingaredis/v1/stats_message.go
This PR applies the following modernized Go fixes made by the [Modernizer Analyzer tool](https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize) with each category fixes committed separately:
- 8eb9913 applies the `efaceany` category: replace interface{} by the 'any' type added in go1.18.
- 643d810 applies the `forvar` category: remove x := x variable declarations made unnecessary by the new semantics of loops in go1.22.
- 4e8db70 applies the `estingcontext` category: replace uses of context.WithCancel in tests with t.Context, added in go1.24.
- c9ebe8c applies the `rangeint` category: replace a 3-clause "for i := 0; i < n; i++" loop by "for i := range n", added in go1.22.
- and lastly ef18863 applies the `stringsseq` category: replace Split in "for range …
> Apply Go's modernized fixes

- cmd/icingadb/main.go
- pkg/icingadb/schema.go
Use a dedicated SQL connection for the schema import to eliminate side effects on future queries.
In particular, the MySQL/MariaDB schema file began by altering SQL system variables, such as "sql_mode". These changes persist throughout the entire connection, affecting every subsequent query.
Our database queries require the ANSI_QUOTES[0] SQL mode. However, the schema file had unset this mode, which resulted in failed queries and a subsequent Icinga DB crash. This was reported independently in #1002 and in the community forum[1].
Creating a short-lived, dedicated SQL connection for the schema import eliminates any impact on the main database connection.
Fixes #1002.
[0]: https://dev.mysql.com/doc/refman/8.4/en/sql-mode.html#sqlmode_ansi_quotes
[1]: …
> Dedicated SQL Connection For Schema Import
